### ISSUE TITLE
Would you mind to share your reference about DBF data structure?

### ISSUE THREAD

**Issue by eugeneYWang** [borysiasty/shapefile_encoding_fixer#2]
Thank you for creating this solution of GIS folks. I have been looking into this issue, and I am wondering if I can solve this in a stand-alone script. 

Some shape files declared itself as UTF-8 in CPG file, but there were problems during the upload of those files to PostGIS. If DBF is truly UTF-8, the problems should not be there. 

I have checked some specification documents on Google, but I cannot find the details of LDID and explanations related to codes I have seen ( pasted below ).

Would you please share your reference of these codes?

```python
        if not ldid:
            encoDesc = '(%s)' % self.tr(u'NOT SET')
        elif ldid == 87:
            encoDesc = '(%s)' % self.tr('Either current ANSI or ISO-8859-1. <u>Usually this is the culprit.</u>')
        elif allLdids.has_key(ldid):
            encoDesc = '(%s %s)' % ( allLdids[ldid][0], allLdids[ldid][1] )
        else:
            encoDesc = '(%s)' % self.tr(u'UNKNOWN')
```

**Comment by borysiasty** [comment]
Hi,
It was years ago and I don't remember any details. Did you google under something like "dbf language driver id"? Wikipedia says it's the 30th byte: https://en.wikipedia.org/wiki/.dbf, then this link:

http://trac.osgeo.org/gdal/browser/branches/1.9/gdal/ogr/ogrsf_frmts/shape/ogrshapelayer.cpp#L170

refers to a list of codes in this Russian page (starting from about half of the page length):

http://www.autopark.ru/ASBProgrammerGuide/DBFSTRUC.HTM

I have no idea if LDID has higher priority over the CPG file, but you can disable it by setting to 0. It's all I know :)
