### ISSUE TITLE
Link for new encoding request is dead

### ISSUE THREAD

**Issue by XRolland** [borysiasty/shapefile_encoding_fixer#5]
In the main window: 

> If you can't find your encoding, please [request it.](http://hub.qgis.org/projects/shpencodingfixer/issues)

The link is dead. I presume it should link to this github page?

Probably need to fix here:
https://github.com/borysiasty/shapefile_encoding_fixer/blob/14f8984b3624b549910854c079a90e1f3f1dd778/shapefile_encoding_fixer/encoding_fixer_plugin.py#LL308C256-L308C314

**Comment by XRolland** [comment]
I don't need a new encoding, but maybe one day a user...
Thanks you for this useful extension!

**Comment by borysiasty** [comment]
Thanks! I just removed that link, one can always find it in the plugin details.
